# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=10000)),
                ('link', models.CharField(max_length=1000)),
                ('mediaurl', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='User',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
        migrations.AddField(
            model_name='news',
            name='abstract',
            field=models.CharField(default=111111, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(default=datetime.datetime(2016, 4, 3, 13, 54, 22, 952715, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=1111111, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.CharField(default=11111, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.CharField(default=111111, max_length=512),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
