# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20160404_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainnewslist',
            name='mediaurl',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='newsdetail',
            name='mediaurl',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='message',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
