# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20160405_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=10000)),
                ('url', models.CharField(max_length=1000)),
                ('mediaurl', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NewsDetail',
        ),
    ]
