# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20160405_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdetails',
            name='mediaurl',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.CharField(default=datetime.datetime(2016, 4, 5, 13, 10, 11, 249198, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
