# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20160405_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='interest',
        ),
        migrations.AddField(
            model_name='mainnewslist',
            name='key',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.CharField(default='Unknow', max_length=100),
        ),
    ]
